version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - git
    - libfuse2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt

# Include all submodules of this project
submodules:
  include: all
